# Generated by Django 2.2.28 on 2022-05-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainlink', models.CharField(max_length=10000)),
                ('linkid', models.CharField(max_length=10)),
            ],
        ),
    ]
